select
    "Longitude (x)"::double as longitude,
    "Latitude (y)"::double as latitude,
    "Station Name"::varchar as station_name,
    "Climate ID"::bigint as climate_id,
    "Date/Time"::date as date_time,
    "Year"::bigint as year,
    "Month"::varchar as month,
    "Day"::varchar as day,
    "Data Quality"::varchar as data_quality,
    "Max Temp (°C)"::double as max_temp_c,
    "Max Temp Flag"::varchar as max_temp_flag,
    "Min Temp (°C)"::double as min_temp_c,
    "Min Temp Flag"::varchar as min_temp_flag,
    "Mean Temp (°C)"::double as mean_temp_c,
    "Mean Temp Flag"::varchar as mean_temp_flag,
    "Heat Deg Days (°C)"::double as heat_deg_days_c,
    "Heat Deg Days Flag"::varchar as heat_deg_days_flag,
    "Cool Deg Days (°C)"::double as cool_deg_days_c,
    "Cool Deg Days Flag"::varchar as cool_deg_days_flag,
    "Total Rain (mm)"::varchar as total_rain_mm,
    "Total Rain Flag"::varchar as total_rain_flag,
    "Total Snow (cm)"::varchar as total_snow_cm,
    "Total Snow Flag"::varchar as total_snow_flag,
    "Total Precip (mm)"::double as total_precip_mm,
    "Total Precip Flag"::varchar as total_precip_flag,
    "Snow on Grnd (cm)"::bigint as snow_on_grnd_cm,
    "Snow on Grnd Flag"::varchar as snow_on_grnd_flag,
    "Dir of Max Gust (10s deg)"::varchar as dir_of_max_gust_10s_deg,
    "Dir of Max Gust Flag"::varchar as dir_of_max_gust_flag,
    "Spd of Max Gust (km/h)"::varchar as spd_of_max_gust_kmh,
    "Spd of Max Gust Flag"::varchar as spd_of_max_gust_flag
from {{ source('weather', 'daily_weather_6158355') }}